name: Java CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout with all branches and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java 14
        uses: joschi/setup-jdk@v2
        with:
          java-version: '14'

      - name: Compile
        run: ./gradlew classes version

      - name: Test
        run: ./gradlew test
